# Run job from local 
- name: Hello World JCL job
  hosts: zoslab
  gather_facts: false
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"
  vars:
    job_owner: IBMUSER
    msg_class: X
    jcl_path: "{{ playbook_dir }}/tmp_jcl"
    jcl_dataset_name: "{{ job_owner }}.TEMP.JCL"

  tasks:
    - name: Render JCL using roles locally on control node
      include_role:
        name: render_jcl_role

    - name: Delete temporary JCL dataset if it exists      
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ jcl_dataset_name }}"
        state: absent

    - name: Allocate temporary JCL dataset
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ jcl_dataset_name }}"
        state: present
        type: seq
        record_format: fb
        record_length: 80
        block_size: 3120
        space_primary: 5
        space_secondary: 1
        space_type: trk

    - name: Copy JCL into dataset (no USS)
      ibm.ibm_zos_core.zos_copy:
        src: "{{ jcl_path }}"
        dest: "{{ jcl_dataset_name }}"
        remote_src: false

    - name: Submit JCL from dataset
      ibm.ibm_zos_core.zos_job_submit:
        src: "{{ jcl_dataset_name }}"
      register: job_result


    - name: Show job id
      ansible.builtin.debug:
        msg: "{{ job_result.jobs[0].job_id }}"